// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userhoster

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	userhoster "rpc-server/rpc/kitex_gen/userhoster"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (err error)
	Login(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (err error)
	SetToken(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (r string, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserhosterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserhosterClient struct {
	*kClient
}

func (p *kUserhosterClient) Register(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, u, h)
}

func (p *kUserhosterClient) Login(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, u, h)
}

func (p *kUserhosterClient) SetToken(ctx context.Context, u *userhoster.User, h *userhoster.Hoster, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetToken(ctx, u, h)
}
